services:
  caddy:
    image: caddy:2.9
    restart: always
    network_mode: host
    volumes:
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/templates:/srv

  fake-backend:
    container_name: fake-backend
    image: vernette/fake-backend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"

  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.11.8
    restart: always
    network_mode: host
    command: -D /var/lib/sing-box -C /etc/sing-box/ run sing-box
    volumes:
      - ./sing-box:/etc/sing-box/
